# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vencalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.setWindowModality(QtCore.Qt.WindowModal)
        Calendar.resize(421, 300)
        self.calendar = QtWidgets.QCalendarWidget(Calendar)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 421, 301))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Seleccion fecha"))
