# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venconf.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venconf(object):
    def setupUi(self, venconf):
        venconf.setObjectName("venconf")
        venconf.resize(400, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(venconf.sizePolicy().hasHeightForWidth())
        venconf.setSizePolicy(sizePolicy)
        venconf.setMinimumSize(QtCore.QSize(400, 180))
        venconf.setMaximumSize(QtCore.QSize(400, 180))
        venconf.setBaseSize(QtCore.QSize(400, 180))
        self.gridLayout = QtWidgets.QGridLayout(venconf)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBox = QtWidgets.QDialogButtonBox(venconf)
        self.btnBox.setOrientation(QtCore.Qt.Horizontal)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnBox.setCenterButtons(True)
        self.btnBox.setObjectName("btnBox")
        self.gridLayout.addWidget(self.btnBox, 5, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblicono = QtWidgets.QLabel(venconf)
        self.lblicono.setMaximumSize(QtCore.QSize(80, 80))
        self.lblicono.setText("")
        self.lblicono.setPixmap(QtGui.QPixmap("img/sad.png"))
        self.lblicono.setScaledContents(True)
        self.lblicono.setObjectName("lblicono")
        self.gridLayout_2.addWidget(self.lblicono, 0, 1, 1, 1)
        self.lblmsgconf = QtWidgets.QLabel(venconf)
        self.lblmsgconf.setAlignment(QtCore.Qt.AlignCenter)
        self.lblmsgconf.setObjectName("lblmsgconf")
        self.gridLayout_2.addWidget(self.lblmsgconf, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)

        self.retranslateUi(venconf)
        self.btnBox.accepted.connect(venconf.accept)
        self.btnBox.rejected.connect(venconf.reject)
        QtCore.QMetaObject.connectSlotsByName(venconf)

    def retranslateUi(self, venconf):
        _translate = QtCore.QCoreApplication.translate
        venconf.setWindowTitle(_translate("venconf", "Está seguro?"))
        self.lblmsgconf.setText(_translate("venconf", "¿Está seguro que desea borrar el usuario?"))
