# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VenPrincipal(object):
    def setupUi(self, VenPrincipal):
        VenPrincipal.setObjectName("VenPrincipal")
        VenPrincipal.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        VenPrincipal.setFont(font)
        self.centralwidget = QtWidgets.QWidget(VenPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_saludo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_saludo.setGeometry(QtCore.QRect(230, 170, 301, 171))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(22)
        font.setUnderline(True)
        self.lbl_saludo.setFont(font)
        self.lbl_saludo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_saludo.setObjectName("lbl_saludo")
        self.btn_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_aceptar.setGeometry(QtCore.QRect(340, 380, 75, 23))
        self.btn_aceptar.setObjectName("btn_aceptar")
        VenPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VenPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        VenPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VenPrincipal)
        self.statusbar.setObjectName("statusbar")
        VenPrincipal.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(VenPrincipal)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(VenPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VenPrincipal)

    def retranslateUi(self, VenPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VenPrincipal.setWindowTitle(_translate("VenPrincipal", "MainWindow"))
        self.lbl_saludo.setText(_translate("VenPrincipal", "Hola mundo"))
        self.btn_aceptar.setText(_translate("VenPrincipal", "Aceptar"))
        self.menuArchivo.setTitle(_translate("VenPrincipal", "Archivo"))
        self.actionSalir.setText(_translate("VenPrincipal", "Salir"))
        self.actionSalir.setShortcut(_translate("VenPrincipal", "Ctrl+S"))
